name: ${name}
version: ${version}
description: Allows a user to repair all mending tools in bulk
author: acomputerdog
main: net.acomputerdog.plugin.PluginMendAll
api-version: 1.13

commands:
  mend:
    description: mends items
    permission: mendall.mend
    usage: Incorrect usage!  Use /mend
    aliases: [mendall, menditems]

permissions:
  mendall.mend:
    description: Allows use of /mend
    default: true